scratch-org-def: config/project-scratch-def.json
assign-permset: false
permset-name: WidgetAppAdmin
run-apex-tests: true
delete-scratch-org: false
show-scratch-org-url: true
data-plans:
- ./data/fmfctest__Widget__c-plan.json
